/**
 * Default configuration for OpenAI calls.
 * Update these values to change the app-wide defaults.
 */
export const OPEN_AI_CONFIG = {
  name: 'Ant',
  model: 'gpt-4o-mini',
  topP: 1,
  temperature: 1,
  systemPrompt: 'You are a helpful assistant.',
  prompt: '',
  maxOutputTokens: 256
};

export const AVAILABLE_MODELS = [
  'gpt-4o-mini',
  'gpt-5',
  'gpt-5-mini'
];

export const CLAUDE_CONFIG = {
  model: 'claude-sonnet-4-20250514',
  topP: 0.8,
  temperature: 1,
  systemPrompt: [
    'You are Claude, the Swarm Orchestrator in an AI Ant Swarm app. Follow this loop strictly:',
    '1) Ask concise clarifying questions until you fully understand the user\'s goal.',
    '2) Write a clear, detailed problem description (2-3 short paragraphs).',
    '3) Ask for permission to deploy the swarm. ONLY after explicit user confirmation, call activate_swarm with problem_description.',
    'When you call activate_swarm, include the final problem_description. Keep normal replies concise. Ask only one set of questions at a time and wait for the user response before asking more.',
  ].join('\n'),
  prompt: '',
  maxOutputTokens: 1024
};

export const DEFAULT_ANT_NAMES = [
  'Blaze',
  'Nova',
  'Echo',
  'Zephyr',
  'Pixel',
  'Dash',
  'Flux',
  'Byte',
  'Spark',
  'Nexus',
  'Quark',
  'Orbit',
  'Cipher',
  'Astra',
  'Vector',
  'Pulse',
  'Glitch',
  'Comet',
  'Drift',
  'Atom',
  'Halo',
  'Quartz',
  'Rift',
  'Neon',
  'Blade',
  'Logic',
  'Volt',
  'Prism',
  'Shift',
  'Core',
  'Kilo',
  'Zenith',
  'Ember',
  'Ion',
  'Apex',
  'Proton',
  'Quantum',
  'Vortex',
  'Sigma',
  'Delta',
  'Gamma',
  'Alpha',
  'Omega',
  'Beta',
  'Orion',
  'Atlas',
  'Titan',
  'Astro',
  'Cosmo',
  'Lynx',
  'Aegis',
  'Nyx',
  'Pyro',
  'Razor',
  'Sable',
  'Talon',
  'Cobalt',
  'Argon',
  'Krypton',
  'Xenon',
  'Radon',
  'Zircon',
  'Onyx',
  'Obsidian',
  'Slate',
  'Graphite',
  'Aurora',
  'Sol',
  'Luna',
  'Terra',
  'Gaia',
  'Aether',
  'Stellar',
  'Meteor',
  'Eclipse',
  'Photon',
  'Laser',
  'Magnet',
  'Turbo',
  'Nitro',
  'Swift',
  'Rapid',
  'Kappa',
  'Lambda',
  'Zeta',
  'Theta',
  'Iota',
  'Mu',
  'Nu',
  'Tau',
  'Rho',
  'Psi',
  'Phi',
  'Chi',
  'Omicron',
  'Upsilon',
  'Epsilon',
  'Zeno',
  'Phoenix',
  'Draco',
];



export default OPEN_AI_CONFIG;


